"use client";
import {useEffect,useMemo,useState} from "react";
type Status="approved"|"review"|"rejected";
type Row={id:number;category:string;supplier:string;channel:string;target:string;confidence:number;status:Status;note?:string;suggested?:string;options?:string[];gate1?:boolean;gate2?:"pass"|"review"|"block"|"n/a"};
type ChannelStatus={channel:string;onChannel:boolean;channelState?:string|null;portalState?:string|null;reviewStatus?:string|null;rejectedReason?:string|null};
type Sample={name:string;id:string;kind:string;parent?:string;rooms:number;beds:number;guests:number;space:string;propertyType?:string;rows:Row[];sourceVersion?:string;syncedAt?:string;recordKind?:"supplier"|"platform";channels?:ChannelStatus[];propertyManager?:string|null;managerContact?:string|null};
const channels=["Booking.com","Vrbo","Expedia"],categories=["Property","Room & beds","Amenities & policies","Validation"];
const shared:Row[]=[
{id:50,category:"Amenities & policies",supplier:"WiFi / all areas / free",channel:"Booking.com",target:"Free WiFi in all areas",confidence:98,status:"approved"},
{id:51,category:"Amenities & policies",supplier:"Parking / private / on-site / $150/stay",channel:"Vrbo",target:"Paid on-site parking",confidence:82,status:"review",note:"Confirm this charge structure; parking reservation is marked NotPossible."},
{id:52,category:"Amenities & policies",supplier:"Pets allowed / free",channel:"Expedia",target:"Pets allowed / no fee",confidence:91,status:"review",note:"Confirm channel eligibility and size/count restrictions."}
];
const single:Row[]=[
{id:1,category:"Property",supplier:"Riverwalk single / PCT34",channel:"Booking.com",target:"Catalog type mapping required",confidence:60,status:"review",note:"usedisplayname=false; confirm public name and PCT34 mapping."},
{id:2,category:"Property",supplier:"Riverwalk single / PCT34",channel:"Vrbo",target:"Catalog type mapping required",confidence:60,status:"review",note:"Do not infer a channel type from the property name."},
{id:3,category:"Room & beds",supplier:"6 rooms / totalBeds=8",channel:"Booking.com",target:"6 bedrooms / 10 configured beds",confidence:20,status:"rejected",note:"Blocking mismatch: bedroomConfiguration contains 10 beds, but totalBeds is 8."},
{id:4,category:"Room & beds",supplier:"RMA113 / RMA58 / RMA86",channel:"Vrbo",target:"Bed catalog lookup required",confidence:65,status:"review",note:"Confirm each bed code and living-room placement."},
{id:5,category:"Amenities & policies",supplier:"HAC312 + 15 RMA codes",channel:"Booking.com",target:"Hotel + room-level mapping",confidence:78,status:"review",note:"Single-unit rule: use applicable values from both catalog levels."},
{id:6,category:"Amenities & policies",supplier:"HAC312 + 15 RMA codes",channel:"Expedia",target:"Map supported; suppress blanks",confidence:78,status:"review",note:"Blank channel mappings mean unsupported."},
...shared,
{id:10,category:"Validation",supplier:"space=111 SQ_FT",channel:"Booking.com",target:"Verify source value/unit",confidence:15,status:"rejected",note:"111 sq ft is implausible for 6 bedrooms and 8 guests. Correct the number or change the unit to SQ_M if that was intended."},
{id:13,category:"Validation",supplier:"rooms=6 / six bedrooms + living room",channel:"Expedia",target:"Confirm rooms means bedrooms",confidence:65,status:"review",note:"The six bedroom objects reconcile to rooms=6, but the API meaning must be explicit so the living room is not counted as a bedroom."},
{id:14,category:"Validation",supplier:"6 bedrooms / bathrooms=1 / toilets=1",channel:"Vrbo",target:"Confirm bathroom count",confidence:60,status:"review",note:"This may be valid, but it is unusual. Verify the bathroom and toilet counts with the supplier."},
{id:15,category:"Validation",supplier:"parking charge = $ 150",channel:"Booking.com",target:"150 USD / per stay",confidence:70,status:"review",note:"Normalize the value into numeric amount, currency, and charge frequency before channel mapping."},
{id:16,category:"Validation",supplier:"Built, renovated, renting dates = 1990-04-26",channel:"Expedia",target:"Confirm or omit unknown dates",confidence:45,status:"review",note:"Three identical dates look like copied or default data. Preserve only dates the supplier can substantiate."},
{id:17,category:"Validation",supplier:"Main description / house rules are placeholder text",channel:"Vrbo",target:"Replace before live onboarding",confidence:40,status:"review",note:"Acceptable for API testing, but not for a client-facing or production channel pilot."},
{id:11,category:"Validation",supplier:"bpValidation=true",channel:"Vrbo",target:"BookingPal validation passed",confidence:100,status:"approved",note:"Channel acceptance remains separate."},
{id:12,category:"Validation",supplier:"Tax number + license expiry 2040-01-01",channel:"Expedia",target:"Compliance fields present",confidence:95,status:"approved"}
];
const multi:Row[]=[
{id:101,category:"Property",supplier:"Riverwalk MLT / PCT34",channel:"Booking.com",target:"MLT child / parent 1335577873",confidence:86,status:"review",note:"altId=55937; confirm parent/child channel structure."},
{id:102,category:"Property",supplier:"notes.name[EN] = House Rules in EN!",channel:"Expedia",target:"Riverwalk MLT",confidence:10,status:"rejected",note:"Blocking issue: translated property name contains house-rules text."},
{id:103,category:"Property",supplier:"Riverwalk MLT / PCT34",channel:"Vrbo",target:"Catalog type mapping required",confidence:60,status:"review"},
{id:104,category:"Room & beds",supplier:"2 rooms / totalBeds=4",channel:"Booking.com",target:"2 bedrooms / 3 configured beds",confidence:20,status:"rejected",note:"Blocking mismatch: bedroomConfiguration contains 3 beds, but totalBeds is 4."},
{id:105,category:"Room & beds",supplier:"RMA113 + RMA58",channel:"Vrbo",target:"Bed catalog lookup required",confidence:65,status:"review",note:"One RMA58 bed is in the living room."},
{id:106,category:"Amenities & policies",supplier:"HAC312 + 4 RMA codes",channel:"Booking.com",target:"Hotel + room-level mapping",confidence:75,status:"review",note:"MLT may require mapping at both levels."},
...shared.map((x,i)=>Object.assign({},x,{id:x.id+100+i})),
{id:110,category:"Validation",supplier:"shortDescription/finePrint: corrupted accented characters",channel:"Expedia",target:"Repair UTF-8 encoding",confidence:10,status:"rejected",note:"Blocking mojibake must be corrected before sync."},
{id:111,category:"Validation",supplier:"persons=3 / childs=2",channel:"Vrbo",target:"Confirm occupancy meaning",confidence:55,status:"review",note:"Confirm whether persons includes children."},
{id:112,category:"Validation",supplier:"No taxNumber on child",channel:"Booking.com",target:"Confirm parent inheritance",confidence:55,status:"review",note:"Verify tax/license data inherits from parent 1335577873. Add it to the child if the channel does not inherit compliance fields."},
{id:115,category:"Validation",supplier:"propertyRating=4.2 / ratingNumber=1111",channel:"Expedia",target:"Verify rating provenance",confidence:55,status:"review",note:"Confirm the rating source is legitimate and permitted for channel distribution."},
{id:116,category:"Validation",supplier:"Descriptions and house rules are test placeholders",channel:"Vrbo",target:"Replace before live onboarding",confidence:40,status:"review",note:"The content is useful for API testing but is not production-quality listing copy."},
{id:117,category:"Validation",supplier:"Raw text may contain UTF-8 mojibake",channel:"Booking.com",target:"Inspect raw response bytes",confidence:50,status:"review",note:"Confirm the corruption exists in the API response and is not only a file-viewer decoding issue before changing stored text."},
{id:113,category:"Validation",supplier:"space=52 SQ_M / bpValidation=true",channel:"Expedia",target:"52 sq m / BookingPal passed",confidence:98,status:"approved"}
];
const samples:Record<string,Sample>={
sgl:{name:"Riverwalk single",id:"1335577872",kind:"Single unit",rooms:6,beds:8,guests:8,space:"111 SQ_FT",propertyType:"PCT34",rows:single},
mlt:{name:"Riverwalk MLT",id:"1335577874",kind:"MLT child",parent:"1335577873",rooms:2,beds:4,guests:3,space:"52 SQ_M",propertyType:"PCT34",rows:multi}
};
const labels:Record<Status,string>={approved:"Approved",review:"Needs review",rejected:"Blocking issue"};
export default function MapwiseClient({user}:{user:{displayName:string;email:string}}){
const[catalog,setCatalog]=useState<Record<string,Sample>>(samples),[key,setKey]=useState("sgl"),[step,setStep]=useState(0),[channel,setChannel]=useState("All channels"),[search,setSearch]=useState(""),[changes,setChanges]=useState<Record<string,Row[]>>({}),[notice,setNotice]=useState(""),[importOpen,setImportOpen]=useState(false),[payload,setPayload]=useState(""),[importError,setImportError]=useState(""),[importing,setImporting]=useState(false),[lookupId,setLookupId]=useState("");
const sample=catalog[key]||samples.sgl,rows=changes[key]||sample.rows,approved=rows.filter(x=>x.status==="approved").length,progress=Math.round(approved/rows.length*100),exceptions=rows.filter(x=>x.status!=="approved");
const visible=useMemo(()=>rows.filter(x=>(channel==="All channels"||x.channel===channel)&&(!search||(x.supplier+" "+x.target+" "+(x.note??"")).toLowerCase().includes(search.toLowerCase()))),[rows,channel,search]);
useEffect(()=>{fetch("/api/properties").then(async response=>{if(!response.ok)throw new Error("Unable to load saved properties.");return response.json() as Promise<{properties:Sample[];decisions:Array<{property_id:string;check_id:string;status:Status;confidence:number}>}>}).then(data=>{const imported:Record<string,Sample>={}; for(const property of data.properties as Sample[]) imported[`api-${property.id}`]=property; const complete={...samples,...imported}; setCatalog(complete); const saved:Record<string,Row[]>={}; for(const [sampleKey,current] of Object.entries(complete)){saved[sampleKey]=current.rows.map(row=>{const decision=(data.decisions as Array<{property_id:string;check_id:string;status:Status;confidence:number}>).find(item=>item.property_id===current.id&&item.check_id===String(row.id)); return decision?{...row,status:decision.status,confidence:decision.confidence}:row})} setChanges(saved)}).catch(()=>setNotice("Saved property data is temporarily unavailable."))},[]);
const approve=async(id:number)=>{const nextRows=rows.map(x=>x.id===id?{...x,status:"approved" as Status,confidence:Math.max(95,x.confidence)}:x);setChanges(o=>({...o,[key]:nextRows}));try{const response=await fetch("/api/decisions",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({propertyId:sample.id,checkId:id,status:"approved",confidence:nextRows.find(x=>x.id===id)?.confidence})});if(!response.ok)throw new Error();setNotice("Decision saved to the internal audit record.")}catch{setNotice("Approval is visible, but could not be saved. Try again.")}setTimeout(()=>setNotice(""),2600)};
const change=(v:string)=>{setKey(v);setStep(0);setChannel("All channels");setSearch("")};
const lookup=()=>{const id=lookupId.trim();if(!id)return;const entry=Object.entries(catalog).find(([,s])=>s.id===id);if(entry){change(entry[0]);setNotice(`Loaded listing ${id}.`)}else{setNotice(`Listing ${id} isn't in the synced set yet — sync it or paste its JSON.`)}setTimeout(()=>setNotice(""),3600)};
const reloadCatalog=async()=>{const response=await fetch("/api/properties");if(!response.ok)return;const data=await response.json() as {properties:Sample[];decisions:Array<{property_id:string;check_id:string;status:Status;confidence:number}>};const imported:Record<string,Sample>={};for(const property of data.properties) imported[`api-${property.id}`]=property;const complete={...samples,...imported};setCatalog(complete);const saved:Record<string,Row[]>={};for(const [sampleKey,current] of Object.entries(complete)){saved[sampleKey]=current.rows.map(row=>{const decision=data.decisions.find(item=>item.property_id===current.id&&item.check_id===String(row.id));return decision?{...row,status:decision.status,confidence:decision.confidence}:row})}setChanges(saved);const firstPlatform=data.properties.find(p=>p.recordKind==="platform");if(firstPlatform)setKey(`api-${firstPlatform.id}`)};
const syncListings=async()=>{setImporting(true);setImportError("");try{let parsed:unknown;try{parsed=JSON.parse(payload)}catch{throw new Error("Paste the sync runner's JSON output.")}
// Accept the runner payload ({listings:[...]}), a bare array, or a single listing object.
const body=Array.isArray(parsed)?{listings:parsed}:(parsed&&typeof parsed==="object"&&"listings"in(parsed as object))?parsed:{listings:[parsed]};const response=await fetch("/api/sync",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});const result=await response.json() as {error?:string;ingested?:number;skipped?:Array<{productId:string;reason:string}>};if(!response.ok)throw new Error(result.error||"Sync failed.");await reloadCatalog();setPayload("");setImportOpen(false);const skippedCount=result.skipped?.length??0;setNotice(`Synced ${result.ingested??0} listing(s)${skippedCount?`, skipped ${skippedCount}`:""}.`);setTimeout(()=>setNotice(""),3200)}catch(error){setImportError(error instanceof Error?error.message:"Sync failed.")}finally{setImporting(false)}};
return <main className="app-shell"><aside className="sidebar"><div className="brand"><span className="brand-mark">M</span><span>Mapwise</span></div><div className="workspace-label">BOOKINGPAL INTERNAL</div><nav><button className="nav-item active"><span>01</span> Client onboarding</button><button className="nav-item" onClick={()=>document.getElementById("all-checks")?.scrollIntoView()}><span>02</span> Exception queue <b className="nav-count">{exceptions.length}</b></button></nav><div className="sidebar-card"><div className="sidebar-card-row"><span>{sample.name}</span><b>{progress}%</b></div><div className="progress-track"><i style={{width:progress+"%"}}/></div><p>{approved} of {rows.length} decisions approved</p></div><div className="user-block"><span className="avatar">{user.displayName.slice(0,2).toUpperCase()}</span><span><b>{user.displayName}</b><small>{user.email}</small></span></div></aside><section className="main-panel">
<header className="topbar"><div className="breadcrumb"><span>{sample.recordKind==="platform"?"Platform sync":"Supplier API"}</span><i>/</i><b>{sample.name}</b><span style={{color:"#8792a2"}}>ID {sample.id}</span></div><div className="top-actions"><label style={{fontSize:10,color:"#657286"}}>Look up ID <input value={lookupId} onChange={e=>setLookupId(e.target.value)} onKeyDown={e=>{if(e.key==="Enter")lookup()}} placeholder="Property ID" style={{height:35,width:118,border:"1px solid #d3dae4",borderRadius:7,padding:"0 9px",marginLeft:7}}/></label><button className="outline-button" onClick={lookup}>Find</button><label style={{fontSize:10,color:"#657286"}}>Property <select value={key} onChange={e=>change(e.target.value)} style={{height:35,border:"1px solid #d3dae4",borderRadius:7,padding:"0 28px 0 9px",marginLeft:7}}>{Object.entries(catalog).map(([value,item])=><option key={value} value={value}>{item.name}</option>)}</select></label><button className="outline-button" onClick={()=>setImportOpen(true)}>Sync platform listings</button><button className="primary-button" onClick={()=>setNotice("Validation rerun across all three channels.")}>Run validation</button></div></header>
<div className="content"><div className="page-heading"><div><span className="eyebrow">{sample.recordKind==="platform"?"PLATFORM SYNC":"SUPPLIER API PILOT"} / {sample.kind.toUpperCase()}</span><h1>Map {sample.name}</h1>{sample.propertyManager&&<p style={{fontSize:12,color:"#48566b",margin:"3px 0 0"}}>Property manager: <b>{sample.propertyManager}</b>{sample.managerContact?` · ${sample.managerContact}`:""}</p>}<p>Review channel mappings and resolve source-data blockers before activation.</p>{sample.syncedAt&&<p style={{fontSize:10,color:"#8994a3",marginTop:4}}>Last sync {sample.syncedAt}{sample.sourceVersion?` · source version ${sample.sourceVersion}`:""}</p>}</div><div className="overall-progress"><span className="progress-number">{progress}%</span><span>Channel ready</span></div></div>
<div style={{display:"grid",gridTemplateColumns:"repeat(7,1fr)",gap:8,margin:"18px 0"}}>{[["TYPE",sample.kind],["PROPERTY ID",sample.id],["PARENT",sample.parent||"N/A"],["ROOMS",String(sample.rooms)],["BEDS",String(sample.beds)],["GUESTS",String(sample.guests)],["SPACE",sample.space]].map(x=><div key={x[0]} style={{background:"#fff",border:"1px solid #dfe5ec",borderRadius:9,padding:11}}><small style={{fontSize:8,color:"#8994a3"}}>{x[0]}</small><b style={{display:"block",fontSize:11,marginTop:5}}>{x[1]}</b></div>)}</div>
<div className="channel-strip">{channels.map((c,i)=>{const cr=rows.filter(x=>x.channel===c);const cs=sample.channels?.find(ch=>ch.channel===c);const statusLabel=cs?(cs.onChannel?`On channel · ${cs.channelState}`:"Not on channel"):"";return <button key={c} className="channel-card" onClick={()=>setChannel(c)}><span className={"channel-logo logo-"+i}>{c[0]}</span><span><b>{c}</b><small>{cr.filter(x=>x.status==="approved").length}/{cr.length} approved{statusLabel?" · "+statusLabel:""}</small></span><i className={"dot "+(cr.some(x=>x.status==="rejected")?"alert":"")}/></button>})}</div>
<div className="stepper">{categories.map((c,i)=><button key={c} className={"step "+(step===i?"active":step>i?"done":"")} onClick={()=>setStep(i)}><span>{step>i?"OK":i+1}</span><b>{c}</b><small>{rows.filter(x=>x.category===c).length} checks</small></button>)}</div><div className="work-grid"><section className="mapping-panel"><div className="panel-heading"><div><h2>{categories[step]}</h2><p>Evidence comes directly from the attached supplier response.</p></div><span className="source-pill">Property {sample.id}</span></div><div className="mapping-stack">{rows.filter(x=>x.category===categories[step]).map(x=><article className="mapping-row" key={x.id}><div className="supplier-value"><small>SUPPLIER VALUE</small><b>{x.supplier}</b><span>{sample.kind} / {sample.propertyType||"Type not provided"}</span></div><div className="mapping-arrow">&rarr;</div><div className="channel-value"><small>{x.channel.toUpperCase()}{x.suggested&&<span style={{marginLeft:6,fontSize:9,fontWeight:600,background:"#eef1fb",color:"#3b5bdb",padding:"1px 6px",borderRadius:9}}>SUGGESTED</span>}{x.gate1===false&&x.target==="No mapping"&&<span style={{marginLeft:6,fontSize:9,fontWeight:600,background:"#fbeaea",color:"#c0392b",padding:"1px 6px",borderRadius:9}}>NO MAPPING</span>}</small>{x.options&&x.options.length>0?<select defaultValue={x.suggested||x.target}>{(x.suggested&&!x.options.includes(x.suggested)?[x.suggested,...x.options]:x.options).map(o=><option key={o}>{o}</option>)}</select>:<select defaultValue={x.target}><option>{x.target}</option><option>Manual configuration required</option><option>Not supported</option></select>}<span className={"confidence "+(x.confidence<85?"low":"")}>{x.confidence}%</span></div><div className="row-action"><span className={"status "+x.status}>{labels[x.status]}</span>{x.status!=="approved"&&<button onClick={()=>approve(x.id)}>Approve</button>}</div>{x.note&&<div className={"mapping-note "+(x.status==="rejected"?"error-note":"")}><b>{x.status==="rejected"?"Resolve before sync":"Review evidence"}</b><span>{x.note}</span></div>}</article>)}</div><div className="panel-footer"><button className="outline-button" disabled={!step} onClick={()=>setStep(s=>s-1)}>Back</button><button className="primary-button" onClick={()=>step<categories.length-1?setStep(s=>s+1):setStep(0)}>{step<categories.length-1?"Save & continue":"Review complete"}</button></div></section><aside className="help-panel"><span className="help-icon">i</span><h3>Payload findings</h3><p>BookingPal validation passed, but channel readiness still requires consistent source data.</p><div className="guidance-rule warning"><span>!</span><p><b>{rows.filter(x=>x.status==="rejected").length} blocking issues</b>Resolve before sync.</p></div><div className="guidance-rule"><span>&#10003;</span><p><b>Real property mode</b>Switch between SGL and MLT above.</p></div></aside></div>
<section id="all-checks" className="table-card" style={{marginTop:16}}><div className="filters"><label className="search-box"><span aria-hidden="true">&#128269;</span><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search payload or resolution"/></label><select value={channel} onChange={e=>setChannel(e.target.value)}><option>All channels</option>{channels.map(c=><option key={c}>{c}</option>)}</select></div><div className="table-wrap"><table><thead><tr><th>Supplier value</th><th>Category</th><th>Channel</th><th>Resolution</th><th>Confidence</th><th>Status</th><th></th></tr></thead><tbody>{visible.map(x=><tr key={x.id}><td><b>{x.supplier}</b><small>{x.note}</small></td><td>{x.category}</td><td>{x.channel}</td><td>{x.target}</td><td><span className={"confidence "+(x.confidence<85?"low":"")}>{x.confidence}%</span></td><td><span className={"status "+x.status}>{labels[x.status]}</span></td><td>{x.status!=="approved"?<button className="approve-link" onClick={()=>approve(x.id)}>Approve</button>:<span className="checkmark">&#10003;</span>}</td></tr>)}</tbody></table></div></section></div></section>{importOpen&&<div className="modal-backdrop" role="presentation"><section className="import-modal" role="dialog" aria-modal="true" aria-labelledby="import-title"><div className="modal-heading"><div><span className="eyebrow">PLATFORM SYNC</span><h2 id="import-title">Sync platform listings</h2><p>Paste the sync runner&rsquo;s JSON output. Only <b>Created</b> listings are ingested; restricted fields never leave the platform database.</p></div><button className="icon-button" aria-label="Close sync" onClick={()=>{setImportOpen(false);setImportError("")}}>x</button></div><textarea value={payload} onChange={event=>setPayload(event.target.value)} placeholder='{"listings":[{"source":{"productId":123,"structure":"SGL","productState":"Created","sourceVersion":"..."},"listing":{...}}]}' autoFocus/><div className="privacy-note"><b>BookingPal employees only</b><span>Syncs and approvals are attributed to {user.email}.</span></div>{importError&&<p className="import-error">{importError}</p>}<div className="modal-actions"><button className="outline-button" onClick={()=>{setImportOpen(false);setImportError("")}}>Cancel</button><button className="primary-button" disabled={importing||!payload.trim()} onClick={syncListings}>{importing?"Syncing...":"Sync listings"}</button></div></section></div>}{notice&&<div className="toast"><span>&#10003;</span>{notice}</div>}</main>
}
